// client-react/src/components/auth/Register.js
import React, { Fragment, useState } from 'react';
import { connect } from 'react-redux';
import { Link, Redirect } from 'react-router-dom';
import { setAlert } from '../../actions/alert';
import { register } from '../../actions/auth';
import PropTypes from 'prop-types';

const Register = ({ setAlert, register, isAuthenticated }) => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    password2: '',
  });
  const { name, email, password, password2 } = formData;
  const onChange = (e) =>
    setFormData({ ...formData, [e.target.name]: e.target.value });
  const onSubmit = async (e) => {
    e.preventDefault();
    if (password !== password2) {
      setAlert('Passwords do not match', 'danger');
    } else {
      register({ name, email, password });
    }
  };
  if (isAuthenticated) {
    return <Redirect to='/dashboard'></Redirect>;
  }
  return (
    <Fragment>
      <h1 className='large text-primary'>Sign Up</h1>
      <p className='lead'>
        <i className='fas fa-user'></i> Create Your Account
      </p>
      <form
        action='dashboard.html'
        className='form'
        onSubmit={(e) => onSubmit(e)}
      >
        <div className='form-group'>
          <input
            type='text'
            value={name}
            name='name'
            onChange={(e) => onChange(e)}
            placeholder='Name'
          />
        </div>
        <div className='form-group'>
          <input
            type='email'
            name='email'
            value={email}
            onChange={(e) => onChange(e)}
            placeholder='Email Address'
          />
          <small className='form-text'>
            This site uses Gravatar, so if you want a profile image, use a
            Gravatar email
          </small>
        </div>
        <div className='form-group'>
          <input
            name='password'
            value={password}
            onChange={(e) => onChange(e)}
            type='password'
            placeholder='Password'
          />
        </div>
        <div className='form-group'>
          <input
            name='password2'
            value={password2}
            onChange={(e) => onChange(e)}
            type='password'
            placeholder='Confirm Password'
          />
        </div>
        <input type='submit' value='Register' className='btn btn-primary' />
      </form>
      <p className='m-1'>
        Already have an account? <Link to='/login'>Sign in</Link>
      </p>
    </Fragment>
  );
};

const mapStateToProps = (state) => ({
  isAuthenticated: state.auth.isAuthenticated,
});

Register.propTypes = {
  setAlert: PropTypes.func.isRequired,
  register: PropTypes.func.isRequired,
  isAuthenticated: PropTypes.bool,
};
export default connect(mapStateToProps, { setAlert, register })(Register);

// client-vue/src/components/auth/Register.vue
<template>
  <div class="container">
    <h1 class="large text-primary">Sign Up</h1>
    <p class="lead"><i class="fas fa-user"></i> Create Your Account</p>
    <form action="dashboard.html" class="form">
      <div class="form-group">
        <input type="text" placeholder="Name" />
      </div>
      <div class="form-group">
        <input type="email" required placeholder="Email Address" />
        <small class="form-text">
          This site uses Gravatar, so if you want a profile image, use a
          Gravatar email
        </small>
      </div>
      <div class="form-group">
        <input minlength="6" type="password" placeholder="Password" />
      </div>
      <div class="form-group">
        <input minlength="6" type="password" placeholder="Confirm Password" />
      </div>
      <input type="submit" value="Register" class="btn btn-primary" />
    </form>
    <p class="m-1">
      Already have an account?
      <router-link to="/login">Sign in</router-link> {{ route }}
    </p>
  </div>
</template>
<script>
import { mapState } from 'vuex';
export default {
  name: 'Register',
  // computed: {
  //   route() {
  //     console.log(this.$router);
  //     return 1;
  //   },
  // },
  computed: mapState({
    routeipc: (state) => state.count,
  }),
  beforeRouteEnter(to, from, next) {
    console.log('helloooooo');
    next();
  },
  beforeRouteLeave(to, from, next) {
    // alert('Hellooooo');
    next();
  },
};
</script>
<style scoped></style>
