// client-vue/src/components/auth/Login.vue
<template>
  <div class="container">
    <div class="alert alert-danger">Invalid Credentials</div>
    <h1 class="large text-primary">Sign In</h1>
    <p class="lead">
      <i class="fas fa-user"></i> Sign into your account
    </p>
    <form action="dashboard.html" class="form">
      <div class="form-group">
        <input type="email" required placeholder="Email Address" />
      </div>
      <div class="form-group">
        <input minlength="6" type="password" placeholder="Password" />
      </div>
      <input type="submit" value="Login" class="btn btn-primary" />
    </form>
    <p class="m-1">
      Don't have an account?
      <router-link to="/register">Sign Up</router-link>
    </p>
  </div>
</template>
<script>
export default {
  name: "Login",
};
</script>
<style scoped>
</style>

// client-react/src/components/auth/Login.js
import React, { Fragment, useState } from 'react';
import { Link, Redirect } from 'react-router-dom';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import { login } from '../../actions/auth';

const Login = ({ login, isAuthenticated }) => {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
  });
  const { email, password } = formData;
  const onChange = (e) =>
    setFormData({ ...formData, [e.target.name]: e.target.value });
  const onSubmit = async (e) => {
    e.preventDefault();
    login(email, password);
  };

  // Redirect if logged in
  if (isAuthenticated) {
    return <Redirect to='/dashboard' />;
  }
  return (
    <Fragment>
      <h1 className='large text-primary'>Sign In</h1>
      <p className='lead'>
        <i className='fas fa-user'></i> Sign into your account
      </p>
      <form
        action='dashboard.html'
        className='form'
        onSubmit={(e) => onSubmit(e)}
      >
        <div className='form-group'>
          <input
            type='email'
            required
            name='email'
            value={email}
            onChange={(e) => onChange(e)}
            placeholder='Email Address'
          />
          <small className='form-text'>
            This site uses Gravatar, so if you want a profile image, use a
            Gravatar email
          </small>
        </div>
        <div className='form-group'>
          <input
            name='password'
            value={password}
            onChange={(e) => onChange(e)}
            minLength='6'
            type='password'
            placeholder='Password'
          />
        </div>
        <input type='submit' value='Login' className='btn btn-primary' />
      </form>
      <p className='m-1'>
        Don't have an account? <Link to='/register'>Sign Up</Link>
      </p>
    </Fragment>
  );
};

Login.propTypes = {
  login: PropTypes.func.isRequired,
  isAuthenticated: PropTypes.bool,
};

const mapStateToProps = (state) => ({
  isAuthenticated: state.auth.isAuthenticated,
});
export default connect(mapStateToProps, { login })(Login);
