// client-vue/src/components/layouts/Landing.vue
<template>
  <section class="landing">
    <div class="dark-overlay">
      <div class="landing-inner">
        <h1 class="x-large">Developer Connector</h1>
        <div class="lead">
          Create Developer profile/portfolio, share posts
          and get help from other developers.
          <div class="buttons">
            <router-link to="/register" class="btn btn-primary">Sign Up</router-link>
            <router-link to="/login" class="btn">Login</router-link>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: "Landing",
};
</script>
<style scoped>
</style>

// client-angular/src/app/components/landing/landing.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-landing',
    styleUrls: ['./landing.component.scss'],
    templateUrl: 'landing.component.html'
})

export class LandingComponent implements OnInit {
    constructor() { }

    ngOnInit() { }
}
<section class="landing">
    <div class="dark-overlay">
          <div class="landing-inner">
              <h1 class="x-large">Developer Connector</h1>

              <div class="lead">
                Create Developer profile/portfolio, share posts
                  and get help from other developers.
                  <div class="buttons">
                      <a routerLink="/register" class="btn btn-primary">Sign Up</a>
                      <a routerLink="/login" class="btn">Login</a>
                  </div>
              </div>
          </div>
    </div>

</section>
