// client-angular/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-navbar',
    styleUrls: ['./navbar.component.scss'],
    templateUrl: 'navbar.component.html'
})

export class NavbarComponent implements OnInit {
    constructor() { }

    ngOnInit() { }
}
<nav class="navbar bg-dark">
      <h1>
        <a href="dashboard.html"> <i class="fas fa-code"></i> DevConnector </a>
      </h1>
      <ul>
        <li><a routerLink="/profiles">Developers</a></li>
        <li><a routerLink="/register">Register</a></li>
        <li><a routerLink="/login">Login</a></li>
      </ul>
    </nav>

// client-vue/src/components/layouts/Navbar.vue
<template>
    <nav class="navbar bg-dark">
      <h1>
        <a href="/"> <i class="fas fa-code"></i> DevConnector </a>
      </h1>
      <ul>
        <li><router-link to="/profiles">Developers</router-link></li>
        <li><router-link to="/register">Register</router-link></li>
        <li><router-link to="/login">Login</router-link></li>
      </ul>
    </nav>
</template>
<script>
    export default {
        name: 'navbar'
    }
</script>
<style scoped>
</style>
